apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: yuriwoofpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yuriwoofpipelinesjavascriptdocker 
    spec:
      containers:
        - name: yuriwoofpipelinesjavascriptdocker 
          image: labplacr.azurecr.io/yuriwoofpipelinesjavascriptdocker
          ports:
          - containerPort: 8080